"""Initial migration

Revision ID: c8b362aa2d83
Revises: 
Create Date: 2025-01-14 03:58:01.284282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b362aa2d83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))
        batch_op.drop_column('title')
        batch_op.drop_column('image_url')
        batch_op.drop_column('additional_images')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_images', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('image')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
